apiVersion: v1
# k8s config file type,
# Secret kind is usually stored in a secured pace
# different than the Depoyment respository
kind: Secret
metadata:
  # random name here
  name: mongodb-secret
# Opaque is the default for arbitrary key/value pairs,
# other types include tls certificates
type: Opaque
# content section to be preserved,
# stored vaue must be in base64 encoded format
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=